// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class "assetsRes {
"
assetsRes._();

static const String PROJECT_NAME = 'ysl_beauty_experience';
static const String PROJECT_VERSION = '1.0.0+1';
static const String " = '"assets/Cafe Le Studio (Activity)/"';
static const String " = '"assets/Fragrance (Product Feature) /"';
static const String " = '"assets/Jardin Majorelle (Activity)/"';
static const String " = '"assets/La Mamounia (Accomodation)/"';
static const String " = '"assets/Ourika Gardens (Activity)/"';
static const String " = '"assets/UI Assets/"';
static const String " = '"assets/YSL Museum
(
Activity
)
/
"
';
}
