// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'ysl_beauty_experience';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String COMPONENTS_CITATION = 'assets/images/components_citation.png';
  static const String COMPONENTS_PRODUCT = 'assets/images/components_product.png';
  static const String EMBRACE = 'assets/images/embrace.png';
  static const String FE9F39E0F744FC911C5572914AAE341D69B71EFD = 'assets/images/fe9f39e0f744fc911c5572914aae341d69b71efd.jpg';
  static const String FRAME_1820549131 = 'assets/images/frame_1820549131.png';
  static const String FRAME_845083589 = 'assets/images/frame_845083589.png';
  static const String FRAME_845083630 = 'assets/images/frame_845083630.png';
  static const String FRAME_845083978 = 'assets/images/frame_845083978.png';
  static const String V23614272648418_LIBRE_EAU_DE_PARFUM_50ML_2_1 = 'assets/images/v23614272648418_libre_eau_de_parfum_50ml_2_1.png';
  static const String SPLASH_SCREEN_OURIKA = 'assets/splash_screen_ourika.mp4';
  static const String LIST = 'assets/svgs/icons/list.svg';
  static const String MAP = 'assets/svgs/icons/map.svg';
  static const String PIN_OPTION_1 = 'assets/svgs/icons/pin_option_1.svg';
  static const String PIN_OPTION_2 = 'assets/svgs/icons/pin_option_2.svg';
  static const String PINYSL_LOGOS = 'assets/svgs/icons/pinysl-logos.svg';
  static const String POSITION_LEFT = 'assets/svgs/icons/position_left.svg';
  static const String POSITION_RIGHT = 'assets/svgs/icons/position_right.svg';
  static const String PROPERTY_1_MOINS = 'assets/svgs/icons/property_1_moins.svg';
  static const String PROPERTY_1_PLUS = 'assets/svgs/icons/property_1_plus.svg';
  static const String SOUNDS = 'assets/svgs/icons/sounds.svg';
  static const String STATE_OFF = 'assets/svgs/icons/state_off.svg';
  static const String STATE_ON = 'assets/svgs/icons/state_on.svg';
  static const String STATE_TOP = 'assets/svgs/icons/state_top.svg';
  static const String VIDEO = 'assets/svgs/icons/video.svg';
  static const String VOLUMESTATE = ON = 'assets/svgs/icons/volumestate=on.svg';
  static const String STATE_LOGO_BEAUT_OFF = 'assets/svgs/logos/state_logo_beaut_off.svg';
  static const String STATE_LOGO_BEAUT_ON = 'assets/svgs/logos/state_logo_beaut_on.svg';
  static const String STATE_MONOGRAMME_BEAUT_OFF = 'assets/svgs/logos/state_monogramme_beaut_off.svg';
  static const String STATE_MONOGRAMME_BEAUT_ON = 'assets/svgs/logos/state_monogramme_beaut_on.svg';
  static const String VERSION_1 = 'assets/svgs/logos/version_1.svg';
  static const String VERSION_2 = 'assets/svgs/logos/version_2.svg';
  static const String VERSION_VERSION5 = 'assets/svgs/logos/version_version5.svg';
}
