// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'ysl_beauty_experience';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CAFE_LE_STUDIO = 'assets/Cafe Le Studio (Activity)/';
  static const String FRAGRANCE_FEATURE = 'assets/Fragrance (Product Feature) /';
  static const String JARDIN_MAJORELLE = 'assets/Jardin Majorelle (Activity)/';
  static const String LA_MAMOUNIA = 'assets/La Mamounia (Accomodation)/';
  static const String OURIKA_GARDENS = 'assets/Ourika Gardens (Activity)/';
  static const String UI_ASSETS = 'assets/UI Assets/';
  static const String YSL_MUSEUM = 'assets/YSL Museum (Activity)/';
}
