// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'ysl_beauty_experience';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ARIAL_BOLD = 'Arial-Bold';
  static const String ARIAL_REGULAR = 'Arial-Regular';
  static const String ITCAVANTGARDEGOTHICPRO_LIGHT = 'ITCAvantGardeGothicPro-Light';
  static const String ITCAVANTGARDESTD_BK = 'ITCAvantGardeStd-Bk';
  static const String ITCAVANTGARDESTD_BOLD = 'ITCAvantGardeStd-Bold';
  static const String ITCAVANTGARDESTD_DEMI = 'ITCAvantGardeStd-Demi';
  static const String ITCAVANTGARDESTD_MD = 'ITCAvantGardeStd-Md';
  static const String ITCAVANTGARDESTD_XLT = 'ITCAvantGardeStd-XLt';
}
